-- AUTO-GENERATED local seed for agent_lo_relationships. Safe to re-run.
CREATE TABLE IF NOT EXISTS public.agent_lo_relationships (
  loan_officer_nmls_id text NOT NULL,
  agent_canonical_id text NOT NULL,
  agent_name text,
  agent_customer_profile_id text,
  brokerage_name text,
  deals_together_30d integer,
  deals_without_you_30d integer,
  other_los_30d integer,
  lo_market_share_30d numeric(5,2),
  volume_30d numeric,
  deals_together_3m integer,
  deals_without_you_3m integer,
  other_los_3m integer,
  lo_market_share_3m numeric(5,2),
  volume_3m numeric,
  deals_together_6m integer,
  deals_without_you_6m integer,
  other_los_6m integer,
  lo_market_share_6m numeric(5,2),
  volume_6m numeric,
  deals_together_7m integer,
  deals_without_you_7m integer,
  other_los_7m integer,
  lo_market_share_7m numeric(5,2),
  volume_7m numeric,
  deals_together_12m integer,
  deals_without_you_12m integer,
  other_los_12m integer,
  lo_market_share_12m numeric(5,2),
  volume_12m numeric,
  deals_together_14m integer,
  deals_without_you_14m integer,
  other_los_14m integer,
  lo_market_share_14m numeric(5,2),
  volume_14m numeric,
  deals_together_2y integer,
  deals_without_you_2y integer,
  other_los_2y integer,
  lo_market_share_2y numeric(5,2),
  volume_2y numeric,
  deals_together_3y integer,
  deals_without_you_3y integer,
  other_los_3y integer,
  lo_market_share_3y numeric(5,2),
  volume_3y numeric,
  deals_together_5y integer,
  deals_without_you_5y integer,
  other_los_5y integer,
  lo_market_share_5y numeric(5,2),
  volume_5y numeric,
  deals_together_ytd integer,
  deals_without_you_ytd integer,
  other_los_ytd integer,
  lo_market_share_ytd numeric(5,2),
  volume_ytd numeric,
  deals_together_py integer,
  deals_without_you_py integer,
  other_los_py integer,
  lo_market_share_py numeric(5,2),
  volume_py numeric,
  deals_together_q1 integer,
  deals_without_you_q1 integer,
  other_los_q1 integer,
  lo_market_share_q1 numeric(5,2),
  volume_q1 numeric,
  deals_together_q2 integer,
  deals_without_you_q2 integer,
  other_los_q2 integer,
  lo_market_share_q2 numeric(5,2),
  volume_q2 numeric,
  deals_together_q3 integer,
  deals_without_you_q3 integer,
  other_los_q3 integer,
  lo_market_share_q3 numeric(5,2),
  volume_q3 numeric,
  deals_together_q4 integer,
  deals_without_you_q4 integer,
  other_los_q4 integer,
  lo_market_share_q4 numeric(5,2),
  volume_q4 numeric,
  PRIMARY KEY (loan_officer_nmls_id, agent_canonical_id)
);

TRUNCATE public.agent_lo_relationships;

INSERT INTO public.agent_lo_relationships (
  loan_officer_nmls_id, agent_canonical_id, agent_name, agent_customer_profile_id, brokerage_name,
  deals_together_30d, deals_without_you_30d, other_los_30d, lo_market_share_30d, volume_30d, deals_together_3m, deals_without_you_3m, other_los_3m, lo_market_share_3m, volume_3m, deals_together_6m, deals_without_you_6m, other_los_6m, lo_market_share_6m, volume_6m, deals_together_7m, deals_without_you_7m, other_los_7m, lo_market_share_7m, volume_7m, deals_together_12m, deals_without_you_12m, other_los_12m, lo_market_share_12m, volume_12m, deals_together_14m, deals_without_you_14m, other_los_14m, lo_market_share_14m, volume_14m, deals_together_2y, deals_without_you_2y, other_los_2y, lo_market_share_2y, volume_2y, deals_together_3y, deals_without_you_3y, other_los_3y, lo_market_share_3y, volume_3y, deals_together_5y, deals_without_you_5y, other_los_5y, lo_market_share_5y, volume_5y, deals_together_ytd, deals_without_you_ytd, other_los_ytd, lo_market_share_ytd, volume_ytd, deals_together_py, deals_without_you_py, other_los_py, lo_market_share_py, volume_py, deals_together_q1, deals_without_you_q1, other_los_q1, lo_market_share_q1, volume_q1, deals_together_q2, deals_without_you_q2, other_los_q2, lo_market_share_q2, volume_q2, deals_together_q3, deals_without_you_q3, other_los_q3, lo_market_share_q3, volume_q3, deals_together_q4, deals_without_you_q4, other_los_q4, lo_market_share_q4, volume_q4
)
SELECT
  base.loan_officer_nmls_id,
  base.agent_canonical_id,
  base.agent_name,
  base.agent_customer_profile_id,
  base.brokerage_name,
    round((1 + (base.h % 9)) * 0.12)::int,
    round((base.h % 15) * 0.12)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.12)::int) / NULLIF((round((1 + (base.h % 9)) * 0.12)::int) + (round((base.h % 15) * 0.12)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.12)::int) * (150000 + (base.h % 350000)))::numeric,
    round((1 + (base.h % 9)) * 0.3)::int,
    round((base.h % 15) * 0.3)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.3)::int) / NULLIF((round((1 + (base.h % 9)) * 0.3)::int) + (round((base.h % 15) * 0.3)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.3)::int) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 0.55)::int, 1),
    round((base.h % 15) * 0.55)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 0.55)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 0.55)::int, 1)) + (round((base.h % 15) * 0.55)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 0.55)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 0.62)::int, 1),
    round((base.h % 15) * 0.62)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 0.62)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 0.62)::int, 1)) + (round((base.h % 15) * 0.62)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 0.62)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 1.0)::int, 1),
    round((base.h % 15) * 1.0)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 1.0)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 1.0)::int, 1)) + (round((base.h % 15) * 1.0)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 1.0)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 1.12)::int, 1),
    round((base.h % 15) * 1.12)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 1.12)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 1.12)::int, 1)) + (round((base.h % 15) * 1.12)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 1.12)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 1.9)::int, 1),
    round((base.h % 15) * 1.9)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 1.9)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 1.9)::int, 1)) + (round((base.h % 15) * 1.9)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 1.9)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 2.6)::int, 1),
    round((base.h % 15) * 2.6)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 2.6)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 2.6)::int, 1)) + (round((base.h % 15) * 2.6)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 2.6)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 3.6)::int, 1),
    round((base.h % 15) * 3.6)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 3.6)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 3.6)::int, 1)) + (round((base.h % 15) * 3.6)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 3.6)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 0.7)::int, 1),
    round((base.h % 15) * 0.7)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 0.7)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 0.7)::int, 1)) + (round((base.h % 15) * 0.7)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 0.7)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    GREATEST(round((1 + (base.h % 9)) * 0.95)::int, 1),
    round((base.h % 15) * 0.95)::int,
    (base.h % 4),
    round(100.0 * (GREATEST(round((1 + (base.h % 9)) * 0.95)::int, 1)) / NULLIF((GREATEST(round((1 + (base.h % 9)) * 0.95)::int, 1)) + (round((base.h % 15) * 0.95)::int), 0), 2),
    ((GREATEST(round((1 + (base.h % 9)) * 0.95)::int, 1)) * (150000 + (base.h % 350000)))::numeric,
    round((1 + (base.h % 9)) * 0.25)::int,
    round((base.h % 15) * 0.25)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.25)::int) / NULLIF((round((1 + (base.h % 9)) * 0.25)::int) + (round((base.h % 15) * 0.25)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.25)::int) * (150000 + (base.h % 350000)))::numeric,
    round((1 + (base.h % 9)) * 0.25)::int,
    round((base.h % 15) * 0.25)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.25)::int) / NULLIF((round((1 + (base.h % 9)) * 0.25)::int) + (round((base.h % 15) * 0.25)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.25)::int) * (150000 + (base.h % 350000)))::numeric,
    round((1 + (base.h % 9)) * 0.25)::int,
    round((base.h % 15) * 0.25)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.25)::int) / NULLIF((round((1 + (base.h % 9)) * 0.25)::int) + (round((base.h % 15) * 0.25)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.25)::int) * (150000 + (base.h % 350000)))::numeric,
    round((1 + (base.h % 9)) * 0.25)::int,
    round((base.h % 15) * 0.25)::int,
    (base.h % 4),
    round(100.0 * (round((1 + (base.h % 9)) * 0.25)::int) / NULLIF((round((1 + (base.h % 9)) * 0.25)::int) + (round((base.h % 15) * 0.25)::int), 0), 2),
    ((round((1 + (base.h % 9)) * 0.25)::int) * (150000 + (base.h % 350000)))::numeric
FROM (
  SELECT
    lo.nmls_id AS loan_officer_nmls_id,
    a.id       AS agent_canonical_id,
    a.full_name AS agent_name,
    a.customer_profile_id AS agent_customer_profile_id,
    a.company  AS brokerage_name,
    abs(hashtext(lo.nmls_id || ':' || a.id)) AS h
  FROM dim_loan_officer lo
  CROSS JOIN (
    SELECT id, full_name, company, customer_profile_id
    FROM dim_agents
    WHERE full_name IS NOT NULL
    ORDER BY id
    LIMIT 8
  ) a
  WHERE lo.nmls_id ~ '^030000'
) base;
